[paths]
model_save_path = "WaterColumnHighlighter/models"
dataset_cache_dir = "WaterColumnHighlighter/models"
checkpoint_dir = "/media/patc/puck_of_destiny/critter_detector/checkpoints"
video_dir = "/home/patc/data/Example_Dive/Compressed"
csv_dir = "/media/patc/puck_of_destiny/patrick_work/Data/Annotations"
mode = "train"
highlight_output_dir = "/media/patc/puck_of_destiny/critter_detector/highlights"
timeline_output_dir = "/media/patc/puck_of_destiny/critter_detector/timelines"
evaluation_output_dir = "/home/patc/data/Example_Dive/evaluation_results"
annotation_csv = "/home/patc/data/Example_Dive/Annotations/SeaTubeAnnotations_20220809T080000.000Z_20220809T200000.000Z.csv"

[training]
window_size = 20        # Number of frames in each input sequence for LSTM model
stride = 1
batch_size = 4
num_epochs = 1
learning_rate = 0.001
k_folds = 5
early_stopping_patience = 10
gradient_clip = 1.0
checkpoint_steps = 1000
scheduler_factor = 0.5
scheduler_patience = 5
optimizer = "Adam"     # Options: "Adam", "SGD", etc.
loss_function = "FocalLoss"  # Options: "FocalLoss", "CrossEntropy", etc.
mixed_precision = true  # New setting

[data]
frame_rate = 29        # Frames per second to sample from videos

[augmentation]
random_crop_size = 200
color_jitter_brightness = 0.1
color_jitter_contrast = 0.1
color_jitter_saturation = 0.1
color_jitter_hue = 0.1

[logging]
wandb_project = "critter_detector"
wandb_entity = "patrickallencooper"
log_interval = 10

[model]
model_type = "lstm"    # Options: "lstm" or "detr"
feature_extractor = "resnet"  # Options for LSTM model: "resnet" or "detr"
fine_tune = false      # Whether to fine-tune the feature extractor or DETR model
hidden_dim = 32        # Hidden dimension size for LSTM
num_layers = 5         # Number of layers for LSTM

[detection]
model = "owl"  # Options: "owl", "yolo", "detr", "clip"
model_variant = "large"  # Options depend on model: for owl: "base", "large"; for yolo: "v8n", "v8s", "v8m", "v8l", "v8x"
score_threshold = 0.2  # Detection confidence threshold
use_ensemble = false    # Whether to use ensemble detection with multiple models
ensemble_weights = { owl = 0.7, yolo = 0.3 }  # Relative weights for ensemble models

[clip]
base_detector = "yolo" # Options: "yolo", "detr"
base_detector_variant = "v8n" # Variant for the base detector (e.g., "v8n", "resnet50")
base_detector_threshold = 0.05 # Confidence threshold for base detector proposals

[aws]
use_aws = false       # Set to true to enable AWS training
s3_bucket_name = "your-s3-bucket-name"
s3_data_prefix = "data/"
aws_region = "us-west-2"

[evaluation]
temporal_tolerance = 30.0  # Time window in seconds for matching detections
simplified_mode = false      # Use single "organism" label instead of detailed categories
skip_organism_filter = true  # Skip positive filtering, only remove operational terms