[paths]
model_save_path = "models"
dataset_cache_dir = "models"
checkpoint_dir = "checkpoints"
video_dir = "videos"
csv_dir = "annotations"
mode = "train"
highlight_output_dir = "highlights"
timeline_output_dir = "timelines"
evaluation_output_dir = "evaluation_results"
annotation_csv = "annotations/example_annotations.csv"
verification_output_dir = "verification_frames"

[training]
window_size = 20        # Number of frames in each input sequence for LSTM model
stride = 1
batch_size = 4
num_epochs = 1
learning_rate = 0.001
k_folds = 5
early_stopping_patience = 10
gradient_clip = 1.0
checkpoint_steps = 1000
scheduler_factor = 0.5
scheduler_patience = 5
optimizer = "Adam"     # Options: "Adam", "SGD", etc.
loss_function = "FocalLoss"  # Options: "FocalLoss", "CrossEntropy", etc.
mixed_precision = true  # New setting

[data]
frame_rate = 29        # Frames per second to sample from videos

[augmentation]
random_crop_size = 200
color_jitter_brightness = 0.1
color_jitter_contrast = 0.1
color_jitter_saturation = 0.1
color_jitter_hue = 0.1

[logging]
wandb_project = "critter_detector"
wandb_entity = "patrickallencooper"
log_interval = 10

[model]
model_type = "lstm"    # Options: "lstm" or "detr"
feature_extractor = "resnet"  # Options for LSTM model: "resnet" or "detr"
fine_tune = false      # Whether to fine-tune the feature extractor or DETR model
hidden_dim = 32        # Hidden dimension size for LSTM
num_layers = 5         # Number of layers for LSTM

[detection]
model = "yoloworld"  # Options: "owl", "yolo", "detr", "clip", "groundingdino", "yoloworld"
model_variant = "l"  # Options: owl(base,l); yolo(v8n-x); detr(res50,101); groundingdino(tiny-m); yoloworld(s,m,l,x,v2-s-x)
score_threshold = 0.25  # Detection confidence threshold
use_ensemble = false    # Whether to use ensemble detection with multiple models
ensemble_weights = { owl = 0.7, yolo = 0.3 }  # Relative weights for ensemble models
labels_csv_path = "marine_labels.csv" # Path to CSV file with organism labels

[clip]
base_detector = "yolo" # Options: "yolo", "detr"
base_detector_variant = "v8n" # Variant for the base detector (e.g., "v8n", "resnet50")
base_detector_threshold = 0.05 # Confidence threshold for base detector proposals

[aws]
use_aws = false       # Set to true to enable AWS training
s3_bucket_name = "your-s3-bucket-name"
s3_data_prefix = "data/"
aws_region = "us-west-2"

[evaluation]
temporal_tolerance = 300.0  # Time window in seconds for matching detections
simplified_mode = false      # Use single "organism" label instead of detailed categories
skip_organism_filter = true  # Skip positive filtering, only remove operational terms

[cuda]
enable_memory_efficient_attention = true
device = 0  # Use GPU device ID 0 (first GPU)
batch_size_limit = 4  # Lower this if experiencing CUDA out-of-memory errors