[paths]
model_save_path = "/Users/patrickcooper/Documents/WaterColumnHighlighter/models"

[training]
batch_size = 4
num_epochs = 10
learning_rate = 0.001
clip_length = 10
hidden_dim = 256
num_layers = 2
k_folds = 5
early_stopping_patience = 10
gradient_clip = 1.0
